version: "3.7"
services:
  postgres_db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d:delegated
  backend:
    build:
      context: ./rust-backend
      dockerfile: Dockerfile
    container_name: rust-app
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./rust-backend:/usr/src/app:delegated
    command: /bin/sh -c "cargo run --release && cargo watch -x run"
    tty: true
    env_file:
      - .env
    environment:
      USER: ${USER}
      CARGO_BUILD_TARGET_DIR: /app/target
      PG.USER: ${PG_USER}
      PG.PASSWORD: ${PG_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
      AUTHORITY: ${AUTHORITY}
      RUST_BACKTRACE: ${RUST_BACKTRACE}
    depends_on:
      - postgres_db

  pgadmin4:
    image: dpage/pgadmin4:5.0
    container_name: pgadmin4
    ports:
      - 8000:80
    volumes:
      - pgadmin4_volume:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    hostname: pgadmin4
    depends_on:
      - postgres_db
    restart: always

volumes:
  postgres_db_volume:
    external: true
  pgadmin4_volume:
    external: true
